# Generated by Django 4.0.2 on 2022-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=50)),
                ('aadhar_no', models.IntegerField(default=0)),
                ('source', models.CharField(default='', max_length=50)),
                ('destination', models.CharField(default='', max_length=50)),
                ('date_of_journey', models.DateField(blank=True, null=True)),
                ('phone_no', models.IntegerField(default=0)),
            ],
        ),
    ]
