# Generated by Django 4.0.2 on 2022-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0002_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='train_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
