# Generated by Django 4.0.2 on 2022-02-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
