# Generated by Django 4.0.2 on 2022-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
